# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffd5cbe82c47e81b35fdc0b0ad159bfd03c88aa7e5ee104c9a7abcabd1c68ace53f98ec081cb546cd0ad5abe67e161e40bfa818a65654ebe57943825ee90653c

test:
  secret_key_base: 82d77f6a6bfd6d8d9ccd7a24d7199a8069cbac7d9f2c99fe1b37eb43be3bed43ab7ad88b509ed05e1da067d65ee02cb24e452f9506a2b2e0e9af7a5c20f606fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
